export const MAIN_PAGE = '/'
export const STARTING_PAGE = '/'
export const SIGN_UP = '/sign_up'
export const LOGIN = '/login'
export const NEW_GOAL = '/new_goal'
export const UPDATE_GOAL = '/update_goal/:goalId'
export const GOAL_DETAILS = '/goal/:goalId'
